### ISSUE TITLE
How to create identities with local accounts?

### ISSUE THREAD

**Issue by filipmartinsson** [EOSEssentials/Scatter#91] opened 2018-06-13 17:52 UTC
I'm trying to use scatter together with my local nodeos. I have added the network 127.0.0.1 with the right port and imported a keypair that is connected to an account that I have locally. But when I try to create an identity in scatter with the local network and that keypair, no accounts show up in scatter. Do I need to do something more in order to get this to work?

Thanks

**Comment by ivan-liljeqvist** [comment] 2018-06-14 07:15
I have this issue too, please hurry

**Comment by nsjames** [comment] 2018-06-15 02:27
Can you guys `curl -XGET http://127.0.0.1:8888/v1/chain/get_info` the chain successfully?

I'm in the process of installing the latest EOSIO on my machine so I'll check here as well.

**Comment by nsjames** [comment] 2018-06-15 03:34
Alright, I've got a VM with nodeos running and I created an account there using cleos called `tester`.
I created a new network inside of Scatter with the ip and port of that "machine" and then imported the keypair into Scatter. Then went to my identity and imported the keypair under that new local network. All seems to run smoothly. 

Going to need a bit more information about the issue you guys are having here.

![image](https://user-images.githubusercontent.com/10360675/41448881-29461da8-7066-11e8-93bb-a3d1e39bbc86.png)

**Comment by filipmartinsson** [comment] 2018-06-15 08:52
Thanks for the reply. The same thing doesn't work for me unfortunately. I'm not running it in a VM though. Is it an issue to have multiple networks? Should I only have the local network in the settings? 

![skarmavbild 2018-06-15 kl 10 50 51](https://user-images.githubusercontent.com/10158281/41459487-07fc0fd0-708a-11e8-9f01-0fe3552f9035.png)
![skarmavbild 2018-06-15 kl 10 50 44](https://user-images.githubusercontent.com/10158281/41459488-082a904e-708a-11e8-9950-e8f2f0478682.png)
![skarmavbild 2018-06-15 kl 10 49 58](https://user-images.githubusercontent.com/10158281/41459490-08944e4e-708a-11e8-8a38-0b45ae623180.png)

**Comment by nsjames** [comment] 2018-06-15 14:38
How about curl, or even just going to http://127.0.0.1/v1/chain/get_info ?

**Comment by gustavomick** [comment] 2018-06-16 23:37
@nsjames having same issue here, confirmed pubs with cleos and get_info with curl. not sure if you have some insights in this one. (also i destroy scatter info and fill this few times to be sure)

**Comment by nsjames** [comment] 2018-06-17 08:51
Weirdness. 
Is there any errors in console? ( before trying to import right click scatter and inspect, then go to console )

**Comment by gustavomick** [comment] 2018-06-17 21:40
@nsjames confirmed, i added history_plugin and started working fine. i would suggest to add that as part as dev setup, since default config.ini configuration is not adding history plugin. thanks

**Comment by nsjames** [comment] 2018-06-17 22:08
Great suggestion, added it to the readme.
I'm gonna go ahead and close this as I think this might have been the issue for all involved.

If it turns out it wasn't post back here and I'll reopen it.

**Closed by nsjames** 2018-06-17 22:08 UTC
